import "./globals.css";
import { Inter } from "next/font/google";
import NavBar from "../components/Navbar";
import Footer from "../components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "CFO By exp_",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={inter.className}>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
